//! Auth sandbox primitives for deterministic credential-based login flows.
//!
//! `AuthScriptEngine` is the low-level deterministic executor that runs inside
//! a one-shot auth worker process. Long-lived services should use
//! `AuthSandboxLauncher`, which spawns a short-lived worker subprocess and keeps
//! raw credential retrieval out of the parent process.

use crate::script_registry::{
    RegistryError, ResolvedScriptProfile, ScriptKind, ScriptMatchKind, ScriptRegistry,
};
use crate::totp::{generate_totp, TotpParams};
use crate::{CredentialVault, GoalScopedVault};
use anyhow::anyhow;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use std::sync::Arc;
use std::time::{Duration, SystemTime, UNIX_EPOCH};
use thiserror::Error;
use tokio::io::AsyncWriteExt;
use tokio::process::Command;

#[derive(Debug, Error)]
pub enum AuthEngineError {
    #[error("no credentials found for service '{0}'")]
    NoCredentials(String),
    #[error("script not found for domain '{0}'")]
    NoScript(#[from] RegistryError),
    #[error("script execution timed out after {0}s")]
    Timeout(u64),
    #[error("script failed: {0}")]
    ScriptFailed(String),
    #[error("invalid script output: {0}")]
    InvalidOutput(String),
    #[error("TOTP generation failed: {0}")]
    TotpFailed(String),
    #[error("auth sandbox unavailable: {0}")]
    SandboxUnavailable(String),
}

/// Input sent to auth scripts via stdin.
#[derive(Debug, Serialize)]
pub struct ScriptInput {
    pub domain: String,
    pub username: String,
    pub password: String,
    /// TOTP code (6 digits), generated by engine. None if no TOTP configured.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub totp_code: Option<String>,
    /// Optional user-supplied continuation input for MFA / captcha / passkey
    /// follow-through after the initial auth step.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub continuation: Option<AuthContinuationInput>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ScriptInputKind {
    TotpCode,
    SmsCode,
    Passkey,
    Captcha,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ScriptInputRequest {
    pub kind: ScriptInputKind,
    pub prompt: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub masked_hint: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AuthContinuationInput {
    pub kind: ScriptInputKind,
    pub value: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
}

#[derive(Debug, Default, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct WorkerRequestEnvelope {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub continuation: Option<AuthContinuationInput>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AuthProfileMatchKind {
    Exact,
    Parent,
    Generic,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AuthProfileScriptKind {
    TypeScript,
    Shell,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AuthExecutionAttestation {
    pub requested_domain: String,
    pub profile_id: String,
    pub match_kind: AuthProfileMatchKind,
    pub script_kind: AuthProfileScriptKind,
    pub script_sha256: String,
}

/// Output expected from auth scripts via stdout.
#[derive(Debug, Serialize, Deserialize)]
pub struct ScriptOutput {
    pub success: bool,
    /// Session token/cookie if successful.
    pub session: Option<String>,
    /// Error message if failed.
    pub error: Option<String>,
    /// Follow-up input requested by the auth profile instead of a terminal
    /// success/failure result.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub input: Option<ScriptInputRequest>,
    /// Opaque script-owned continuation state to echo back on
    /// `credential.respond`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub continuation_state: Option<String>,
    /// Trusted worker-attested metadata about the resolved auth profile.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attestation: Option<AuthExecutionAttestation>,
}

/// Auth Script Engine configuration.
pub struct AuthEngineConfig {
    /// Maximum time to wait for a script to complete.
    pub timeout: Duration,
    /// Root directory for auth scripts (used as `current_dir` for Node.js).
    /// When set, TypeScript scripts resolve `node_modules` from here.
    pub scripts_dir: Option<std::path::PathBuf>,
    /// Custom path to the Node.js binary directory.
    /// When set, this is prepended to `PATH` for `.ts` script execution.
    pub node_bin: Option<std::path::PathBuf>,
}

/// Configuration for the one-shot auth sandbox launcher.
#[derive(Debug, Clone)]
pub struct AuthSandboxLauncherConfig {
    /// Path to the worker binary to spawn.
    pub worker_bin: PathBuf,
    /// Root directory containing the goal-scoped credential vault.
    pub vault_root: PathBuf,
    /// Root directory containing auth scripts.
    pub scripts_dir: PathBuf,
    /// Maximum time to wait for a worker to complete.
    pub timeout: Duration,
    /// Optional path to Node.js bin directory for TypeScript script execution.
    pub node_bin: Option<PathBuf>,
    /// Optional goal scope to constrain credential access.
    pub goal_scope: Option<String>,
}

/// Configuration used inside the one-shot auth worker.
#[derive(Debug, Clone)]
pub struct AuthSandboxWorkerConfig {
    pub vault_root: PathBuf,
    pub scripts_dir: PathBuf,
    pub timeout: Duration,
    pub node_bin: Option<PathBuf>,
    pub goal_scope: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct WorkerResultEnvelope {
    pub ok: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output: Option<ScriptOutput>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_kind: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_domain: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timeout_secs: Option<u64>,
}

impl Default for AuthEngineConfig {
    fn default() -> Self {
        Self {
            timeout: Duration::from_secs(60),
            scripts_dir: None,
            node_bin: None,
        }
    }
}

/// Spawns a one-shot auth worker subprocess so raw credential retrieval happens
/// only inside that dedicated short-lived process.
#[derive(Clone)]
pub struct AuthSandboxLauncher {
    registry: ScriptRegistry,
    config: AuthSandboxLauncherConfig,
}

impl AuthSandboxLauncher {
    pub fn new(registry: ScriptRegistry, config: AuthSandboxLauncherConfig) -> Self {
        Self { registry, config }
    }

    pub fn resolve_attestation(
        &self,
        domain: &str,
    ) -> Result<AuthExecutionAttestation, AuthEngineError> {
        let resolved = self.registry.resolve_profile(domain)?;
        Ok(auth_execution_attestation(&resolved))
    }

    pub async fn authenticate(&self, domain: &str) -> Result<ScriptOutput, AuthEngineError> {
        self.authenticate_scoped(domain, self.config.goal_scope.as_deref())
            .await
    }

    pub async fn authenticate_scoped(
        &self,
        domain: &str,
        goal_scope: Option<&str>,
    ) -> Result<ScriptOutput, AuthEngineError> {
        self.authenticate_with_response_scoped(domain, goal_scope, None)
            .await
    }

    pub async fn authenticate_with_response_scoped(
        &self,
        domain: &str,
        goal_scope: Option<&str>,
        continuation: Option<AuthContinuationInput>,
    ) -> Result<ScriptOutput, AuthEngineError> {
        // Validate that a concrete script or fallback exists before spawning.
        self.registry.resolve_profile(domain)?;

        let mut cmd = Command::new(&self.config.worker_bin);
        cmd.arg("auth-sandbox-run")
            .arg("--vault-root")
            .arg(&self.config.vault_root)
            .arg("--scripts-dir")
            .arg(&self.config.scripts_dir)
            .arg("--domain")
            .arg(domain)
            .arg("--timeout-secs")
            .arg(self.config.timeout.as_secs().to_string())
            .stdin(std::process::Stdio::piped())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped());

        if let Some(ref node_bin) = self.config.node_bin {
            cmd.arg("--node-bin").arg(node_bin);
        }
        if let Some(goal_scope) = goal_scope.or(self.config.goal_scope.as_deref()) {
            cmd.arg("--goal-scope").arg(goal_scope);
        }

        let mut child = cmd
            .spawn()
            .map_err(|e| AuthEngineError::SandboxUnavailable(format!("spawn failed: {e}")))?;

        let request_json =
            serde_json::to_string(&WorkerRequestEnvelope { continuation }).map_err(|e| {
                AuthEngineError::SandboxUnavailable(format!("stdin encode failed: {e}"))
            })?;
        if let Some(mut stdin) = child.stdin.take() {
            stdin
                .write_all(request_json.as_bytes())
                .await
                .map_err(|e| {
                    AuthEngineError::SandboxUnavailable(format!("stdin write failed: {e}"))
                })?;
        }

        let output = child
            .wait_with_output()
            .await
            .map_err(|e| AuthEngineError::SandboxUnavailable(format!("wait failed: {e}")))?;

        let stdout = String::from_utf8_lossy(&output.stdout);
        let envelope: WorkerResultEnvelope = serde_json::from_str(&stdout).map_err(|e| {
            let stderr = String::from_utf8_lossy(&output.stderr);
            AuthEngineError::InvalidOutput(format!(
                "{e}: stdout=`{}` stderr=`{}`",
                stdout.trim(),
                stderr.trim()
            ))
        })?;

        if envelope.ok {
            return envelope.output.ok_or_else(|| {
                AuthEngineError::InvalidOutput("worker response missing output".to_string())
            });
        }

        Err(decode_worker_error(
            envelope.error_kind.as_deref().unwrap_or("ScriptFailed"),
            envelope
                .error_message
                .unwrap_or_else(|| "unknown auth sandbox error".to_string()),
            envelope.error_domain,
            envelope.timeout_secs,
        ))
    }
}

/// Engine that drives auth scripts with credentials from the vault.
pub struct AuthScriptEngine {
    registry: ScriptRegistry,
    vault: Arc<dyn CredentialVault>,
    config: AuthEngineConfig,
}

/// Executes a one-shot auth worker request by opening the scoped vault and
/// running the deterministic auth script locally inside the worker process.
pub async fn run_auth_sandbox_worker(
    config: AuthSandboxWorkerConfig,
    domain: &str,
    continuation: Option<AuthContinuationInput>,
) -> Result<ScriptOutput, AuthEngineError> {
    let registry = ScriptRegistry::from_dir(&config.scripts_dir)
        .map_err(|e| AuthEngineError::SandboxUnavailable(e.to_string()))?;
    let scoped_vault = GoalScopedVault::open(&config.vault_root)
        .map_err(|e| AuthEngineError::SandboxUnavailable(e.to_string()))?;
    let vault = scoped_vault
        .vault_for_scope(config.goal_scope.as_deref())
        .map_err(|e| AuthEngineError::SandboxUnavailable(e.to_string()))?;
    let engine = AuthScriptEngine::new(
        registry,
        vault,
        AuthEngineConfig {
            timeout: config.timeout,
            scripts_dir: Some(config.scripts_dir),
            node_bin: config.node_bin,
        },
    );
    match continuation {
        Some(continuation) => engine.continue_authenticate(domain, continuation).await,
        None => engine.authenticate(domain).await,
    }
}

pub fn encode_worker_result(
    result: Result<ScriptOutput, AuthEngineError>,
) -> Result<String, anyhow::Error> {
    let envelope = match result {
        Ok(output) => WorkerResultEnvelope {
            ok: true,
            output: Some(output),
            error_kind: None,
            error_message: None,
            error_domain: None,
            timeout_secs: None,
        },
        Err(error) => {
            let (error_domain, timeout_secs) = worker_error_context(&error);
            WorkerResultEnvelope {
                ok: false,
                output: None,
                error_kind: Some(worker_error_kind(&error).to_string()),
                error_message: Some(error.to_string()),
                error_domain,
                timeout_secs,
            }
        }
    };
    serde_json::to_string(&envelope).map_err(|e| anyhow!(e))
}

fn worker_error_kind(error: &AuthEngineError) -> &'static str {
    match error {
        AuthEngineError::NoCredentials(_) => "NoCredentials",
        AuthEngineError::NoScript(_) => "NoScript",
        AuthEngineError::Timeout(_) => "Timeout",
        AuthEngineError::ScriptFailed(_) => "ScriptFailed",
        AuthEngineError::InvalidOutput(_) => "InvalidOutput",
        AuthEngineError::TotpFailed(_) => "TotpFailed",
        AuthEngineError::SandboxUnavailable(_) => "SandboxUnavailable",
    }
}

fn worker_error_context(error: &AuthEngineError) -> (Option<String>, Option<u64>) {
    match error {
        AuthEngineError::NoScript(RegistryError::NoScript(domain)) => (Some(domain.clone()), None),
        AuthEngineError::Timeout(timeout_secs) => (None, Some(*timeout_secs)),
        _ => (None, None),
    }
}

fn decode_worker_error(
    kind: &str,
    message: String,
    error_domain: Option<String>,
    timeout_secs: Option<u64>,
) -> AuthEngineError {
    match kind {
        "NoCredentials" => AuthEngineError::NoCredentials(message),
        "NoScript" => {
            AuthEngineError::NoScript(RegistryError::NoScript(error_domain.unwrap_or(message)))
        }
        "Timeout" => AuthEngineError::Timeout(timeout_secs.unwrap_or(0)),
        "InvalidOutput" => AuthEngineError::InvalidOutput(message),
        "TotpFailed" => AuthEngineError::TotpFailed(message),
        "SandboxUnavailable" => AuthEngineError::SandboxUnavailable(message),
        _ => AuthEngineError::ScriptFailed(message),
    }
}

impl AuthScriptEngine {
    pub fn new(
        registry: ScriptRegistry,
        vault: Arc<dyn CredentialVault>,
        config: AuthEngineConfig,
    ) -> Self {
        Self {
            registry,
            vault,
            config,
        }
    }

    /// Execute authentication for a domain.
    /// Returns the script output on success.
    pub async fn authenticate(&self, domain: &str) -> Result<ScriptOutput, AuthEngineError> {
        self.authenticate_with_response(domain, None).await
    }

    pub async fn continue_authenticate(
        &self,
        domain: &str,
        continuation: AuthContinuationInput,
    ) -> Result<ScriptOutput, AuthEngineError> {
        self.authenticate_with_response(domain, Some(continuation))
            .await
    }

    async fn authenticate_with_response(
        &self,
        domain: &str,
        continuation: Option<AuthContinuationInput>,
    ) -> Result<ScriptOutput, AuthEngineError> {
        // 1. Get credentials from vault
        let credential = self
            .vault
            .get(domain)
            .map_err(|e| AuthEngineError::ScriptFailed(e.to_string()))?
            .ok_or_else(|| AuthEngineError::NoCredentials(domain.to_string()))?;

        // 2. Generate TOTP code if secret is present
        let totp_code = if let Some(ref totp_secret) = credential.totp_secret {
            let now = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .map_err(|e| AuthEngineError::TotpFailed(e.to_string()))?
                .as_secs();
            let code = generate_totp(totp_secret, now, &TotpParams::default())
                .map_err(|e| AuthEngineError::TotpFailed(e.to_string()))?;
            Some(code)
        } else {
            None
        };

        // 3. Build script input
        let input = ScriptInput {
            domain: domain.to_string(),
            username: credential.username.clone(),
            password: credential.secret.clone(),
            totp_code,
            continuation,
        };

        // 4. Resolve script path
        let resolved = self.registry.resolve_profile(domain)?;

        // 5. Spawn script subprocess with timeout
        let input_json = serde_json::to_string(&input)
            .map_err(|e| AuthEngineError::ScriptFailed(e.to_string()))?;

        let timeout_secs = self.config.timeout.as_secs();
        let result =
            tokio::time::timeout(self.config.timeout, self.run_script(resolved, input_json))
                .await
                .map_err(|_| AuthEngineError::Timeout(timeout_secs))?;

        result
    }

    async fn run_script(
        &self,
        resolved: ResolvedScriptProfile,
        input_json: String,
    ) -> Result<ScriptOutput, AuthEngineError> {
        let script_path = resolved.path.clone();
        let is_typescript = script_path
            .extension()
            .and_then(|e| e.to_str())
            .is_some_and(|ext| ext == "ts");

        let mut cmd = if is_typescript {
            let mut c = Command::new("npx");
            c.arg("ts-node").arg("--esm").arg(&script_path);
            c
        } else {
            Command::new(&script_path)
        };

        cmd.stdin(std::process::Stdio::piped())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            // Don't pass credentials through env
            .env_clear();

        // Build PATH — optionally prepend custom node_bin directory
        let system_path = std::env::var("PATH").unwrap_or_default();
        let path = if let Some(ref node_bin) = self.config.node_bin {
            format!("{}:{}", node_bin.display(), system_path)
        } else {
            system_path
        };
        cmd.env("PATH", path);

        // HOME is needed by Node.js for config/cache directories
        if let Ok(home) = std::env::var("HOME") {
            cmd.env("HOME", home);
        }

        // Set working directory to scripts_dir so Node.js resolves node_modules
        if let Some(ref scripts_dir) = self.config.scripts_dir {
            cmd.current_dir(scripts_dir);
        }

        let mut child = cmd
            .spawn()
            .map_err(|e| AuthEngineError::ScriptFailed(format!("spawn failed: {e}")))?;

        // Write input to stdin. If the script exits before reading (e.g. a
        // script that ignores credentials and returns a static JSON result),
        // the write races with the child's exit and we may see BrokenPipe on
        // Linux. Treat that specifically as "child didn't want input" — its
        // exit status + stdout below still dictate the result. Any other IO
        // error stays fatal.
        if let Some(mut stdin) = child.stdin.take() {
            if let Err(e) = stdin.write_all(input_json.as_bytes()).await {
                if e.kind() != std::io::ErrorKind::BrokenPipe {
                    return Err(AuthEngineError::ScriptFailed(format!(
                        "stdin write failed: {e}"
                    )));
                }
            }
            // Drop stdin to signal EOF
        }

        // Wait for completion
        let output = child
            .wait_with_output()
            .await
            .map_err(|e| AuthEngineError::ScriptFailed(format!("wait failed: {e}")))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(AuthEngineError::ScriptFailed(format!(
                "exit code {}: {}",
                output.status,
                stderr.trim()
            )));
        }

        // Parse stdout JSON
        let stdout = String::from_utf8_lossy(&output.stdout);
        let mut parsed = serde_json::from_str::<ScriptOutput>(&stdout)
            .map_err(|e| AuthEngineError::InvalidOutput(format!("{e}: {}", stdout.trim())))?;
        parsed.attestation = Some(auth_execution_attestation(&resolved));
        Ok(parsed)
    }
}

fn auth_execution_attestation(resolved: &ResolvedScriptProfile) -> AuthExecutionAttestation {
    AuthExecutionAttestation {
        requested_domain: resolved.requested_domain.clone(),
        profile_id: resolved.profile_id.clone(),
        match_kind: match resolved.match_kind {
            ScriptMatchKind::Exact => AuthProfileMatchKind::Exact,
            ScriptMatchKind::Parent => AuthProfileMatchKind::Parent,
            ScriptMatchKind::Generic => AuthProfileMatchKind::Generic,
        },
        script_kind: match resolved.script_kind {
            ScriptKind::TypeScript => AuthProfileScriptKind::TypeScript,
            ScriptKind::Shell => AuthProfileScriptKind::Shell,
        },
        script_sha256: resolved.sha256.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::script_registry::ScriptRegistry;
    use crate::{CredentialRecord, CredentialVault};
    use anyhow::Result;
    use std::path::PathBuf;

    /// In-memory vault for testing.
    struct MockVault {
        records: std::sync::Mutex<std::collections::HashMap<String, CredentialRecord>>,
    }

    impl MockVault {
        fn new() -> Self {
            Self {
                records: std::sync::Mutex::new(std::collections::HashMap::new()),
            }
        }

        fn insert(&self, record: CredentialRecord) {
            self.records
                .lock()
                .expect("lock")
                .insert(record.service.clone(), record);
        }
    }

    impl CredentialVault for MockVault {
        fn put(&self, credential: CredentialRecord) -> Result<()> {
            self.records
                .lock()
                .expect("lock")
                .insert(credential.service.clone(), credential);
            Ok(())
        }

        fn get(&self, service: &str) -> Result<Option<CredentialRecord>> {
            Ok(self.records.lock().expect("lock").get(service).cloned())
        }

        fn delete(&self, service: &str) -> Result<bool> {
            Ok(self.records.lock().expect("lock").remove(service).is_some())
        }

        fn list_services(&self) -> Result<Vec<String>> {
            Ok(self.records.lock().expect("lock").keys().cloned().collect())
        }
    }

    /// Create a mock script that echoes a success response.
    fn create_success_script(dir: &std::path::Path) -> PathBuf {
        let script_path = dir.join("mock.sh");
        std::fs::write(
            &script_path,
            r#"#!/bin/sh
# Read stdin (credentials), write success JSON to stdout
INPUT=$(cat)
echo '{"success": true, "session": "mock_session_token"}'
"#,
        )
        .expect("write script");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&script_path, std::fs::Permissions::from_mode(0o755))
                .expect("chmod");
        }
        script_path
    }

    /// Create a mock script that returns a failure response.
    fn create_failure_script(dir: &std::path::Path) -> PathBuf {
        let script_path = dir.join("fail.sh");
        std::fs::write(
            &script_path,
            r#"#!/bin/sh
echo '{"success": false, "error": "Invalid credentials"}'
"#,
        )
        .expect("write script");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&script_path, std::fs::Permissions::from_mode(0o755))
                .expect("chmod");
        }
        script_path
    }

    /// Create a mock script that exits with non-zero.
    fn create_crash_script(dir: &std::path::Path) -> PathBuf {
        let script_path = dir.join("crash.sh");
        std::fs::write(
            &script_path,
            "#!/bin/sh\necho 'something broke' >&2\nexit 1\n",
        )
        .expect("write script");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&script_path, std::fs::Permissions::from_mode(0o755))
                .expect("chmod");
        }
        script_path
    }

    /// Create a script that sleeps longer than the timeout.
    fn create_slow_script(dir: &std::path::Path) -> PathBuf {
        let script_path = dir.join("slow.sh");
        std::fs::write(
            &script_path,
            "#!/bin/sh\nsleep 30\necho '{\"success\": true}'\n",
        )
        .expect("write script");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&script_path, std::fs::Permissions::from_mode(0o755))
                .expect("chmod");
        }
        script_path
    }

    /// Create a script that saves stdin to a sidecar file for test inspection.
    /// Returns (script_path, sidecar_path) — test reads sidecar to verify input.
    fn create_stdin_capture_script(dir: &std::path::Path) -> (PathBuf, PathBuf) {
        let script_path = dir.join("capture.sh");
        let sidecar_path = dir.join("captured_stdin.json");
        let script_content = format!(
            "#!/bin/sh\ncat > '{}'\necho '{{\"success\": true, \"session\": \"captured\"}}'\n",
            sidecar_path.display()
        );
        std::fs::write(&script_path, script_content).expect("write script");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&script_path, std::fs::Permissions::from_mode(0o755))
                .expect("chmod");
        }
        (script_path, sidecar_path)
    }

    #[tokio::test]
    async fn authenticate_success() {
        let dir = tempfile::tempdir().expect("tempdir");
        let script = create_success_script(dir.path());

        let mut registry = ScriptRegistry::empty();
        registry.register("example.com", script);

        let vault = Arc::new(MockVault::new());
        vault.insert(CredentialRecord {
            service: "example.com".to_string(),
            username: "user".to_string(),
            secret: "pass".to_string(),
            totp_secret: None,
        });

        let engine = AuthScriptEngine::new(registry, vault, AuthEngineConfig::default());
        let result = engine.authenticate("example.com").await.expect("auth");
        assert!(result.success);
        assert_eq!(result.session.as_deref(), Some("mock_session_token"));
        let attestation = result.attestation.expect("attestation should be present");
        assert_eq!(attestation.requested_domain, "example.com");
        assert_eq!(attestation.profile_id, "example.com");
        assert_eq!(attestation.match_kind, AuthProfileMatchKind::Exact);
        assert_eq!(attestation.script_kind, AuthProfileScriptKind::Shell);
        assert_eq!(attestation.script_sha256.len(), 64);
    }

    #[tokio::test]
    async fn authenticate_script_failure_output() {
        let dir = tempfile::tempdir().expect("tempdir");
        let script = create_failure_script(dir.path());

        let mut registry = ScriptRegistry::empty();
        registry.register("example.com", script);

        let vault = Arc::new(MockVault::new());
        vault.insert(CredentialRecord {
            service: "example.com".to_string(),
            username: "user".to_string(),
            secret: "pass".to_string(),
            totp_secret: None,
        });

        let engine = AuthScriptEngine::new(registry, vault, AuthEngineConfig::default());
        let result = engine.authenticate("example.com").await.expect("auth");
        assert!(!result.success);
        assert_eq!(result.error.as_deref(), Some("Invalid credentials"));
    }

    #[tokio::test]
    async fn authenticate_script_crash() {
        let dir = tempfile::tempdir().expect("tempdir");
        let script = create_crash_script(dir.path());

        let mut registry = ScriptRegistry::empty();
        registry.register("example.com", script);

        let vault = Arc::new(MockVault::new());
        vault.insert(CredentialRecord {
            service: "example.com".to_string(),
            username: "user".to_string(),
            secret: "pass".to_string(),
            totp_secret: None,
        });

        let engine = AuthScriptEngine::new(registry, vault, AuthEngineConfig::default());
        let err = engine.authenticate("example.com").await.unwrap_err();
        assert!(matches!(err, AuthEngineError::ScriptFailed(_)));
        let msg = err.to_string();
        assert!(msg.contains("something broke"), "got: {msg}");
    }

    #[tokio::test]
    async fn authenticate_no_credentials() {
        let mut registry = ScriptRegistry::empty();
        registry.register("example.com", PathBuf::from("/nonexistent/script.sh"));

        let vault = Arc::new(MockVault::new());
        // No credentials inserted

        let engine = AuthScriptEngine::new(registry, vault, AuthEngineConfig::default());
        let err = engine.authenticate("example.com").await.unwrap_err();
        assert!(matches!(err, AuthEngineError::NoCredentials(_)));
    }

    #[tokio::test]
    async fn authenticate_no_script() {
        let registry = ScriptRegistry::empty();
        // No scripts registered

        let vault = Arc::new(MockVault::new());
        vault.insert(CredentialRecord {
            service: "example.com".to_string(),
            username: "user".to_string(),
            secret: "pass".to_string(),
            totp_secret: None,
        });

        let engine = AuthScriptEngine::new(registry, vault, AuthEngineConfig::default());
        let err = engine.authenticate("example.com").await.unwrap_err();
        assert!(matches!(err, AuthEngineError::NoScript(_)));
    }

    #[tokio::test]
    async fn authenticate_timeout() {
        let dir = tempfile::tempdir().expect("tempdir");
        let script = create_slow_script(dir.path());

        let mut registry = ScriptRegistry::empty();
        registry.register("example.com", script);

        let vault = Arc::new(MockVault::new());
        vault.insert(CredentialRecord {
            service: "example.com".to_string(),
            username: "user".to_string(),
            secret: "pass".to_string(),
            totp_secret: None,
        });

        let config = AuthEngineConfig {
            timeout: Duration::from_millis(100),
            ..AuthEngineConfig::default()
        };
        let engine = AuthScriptEngine::new(registry, vault, config);
        let err = engine.authenticate("example.com").await.unwrap_err();
        assert!(matches!(err, AuthEngineError::Timeout(_)));
    }

    #[test]
    fn worker_result_preserves_no_script_error_kind() {
        let payload = encode_worker_result(Err(AuthEngineError::NoScript(
            RegistryError::NoScript("example.com".to_string()),
        )))
        .expect("encode worker result");
        let envelope: WorkerResultEnvelope =
            serde_json::from_str(&payload).expect("decode envelope");

        let error = decode_worker_error(
            envelope.error_kind.as_deref().expect("error kind"),
            envelope.error_message.expect("error message"),
            envelope.error_domain,
            envelope.timeout_secs,
        );
        assert!(matches!(
            error,
            AuthEngineError::NoScript(RegistryError::NoScript(ref domain))
                if domain == "example.com"
        ));
    }

    #[test]
    fn worker_result_preserves_timeout_seconds() {
        let payload =
            encode_worker_result(Err(AuthEngineError::Timeout(42))).expect("encode worker result");
        let envelope: WorkerResultEnvelope =
            serde_json::from_str(&payload).expect("decode envelope");

        let error = decode_worker_error(
            envelope.error_kind.as_deref().expect("error kind"),
            envelope.error_message.expect("error message"),
            envelope.error_domain,
            envelope.timeout_secs,
        );
        assert!(matches!(error, AuthEngineError::Timeout(42)));
    }

    #[tokio::test]
    async fn authenticate_passes_credentials_via_stdin() {
        let dir = tempfile::tempdir().expect("tempdir");
        let (script, sidecar) = create_stdin_capture_script(dir.path());

        let mut registry = ScriptRegistry::empty();
        registry.register("example.com", script);

        let vault = Arc::new(MockVault::new());
        vault.insert(CredentialRecord {
            service: "example.com".to_string(),
            username: "testuser".to_string(),
            secret: "testpass".to_string(),
            totp_secret: None,
        });

        let engine = AuthScriptEngine::new(registry, vault, AuthEngineConfig::default());
        let result = engine.authenticate("example.com").await.expect("auth");
        assert!(result.success);

        // Read the captured stdin from the sidecar file
        let captured = std::fs::read_to_string(&sidecar).expect("read sidecar");
        let input: serde_json::Value =
            serde_json::from_str(&captured).expect("parse captured input");
        assert_eq!(input["domain"], "example.com");
        assert_eq!(input["username"], "testuser");
        assert_eq!(input["password"], "testpass");
        // No TOTP configured, so totp_code should be absent
        assert!(input.get("totp_code").is_none());
    }

    #[tokio::test]
    async fn continue_authenticate_passes_continuation_via_stdin() {
        let dir = tempfile::tempdir().expect("tempdir");
        let (script, sidecar) = create_stdin_capture_script(dir.path());

        let mut registry = ScriptRegistry::empty();
        registry.register("example.com", script);

        let vault = Arc::new(MockVault::new());
        vault.insert(CredentialRecord {
            service: "example.com".to_string(),
            username: "testuser".to_string(),
            secret: "testpass".to_string(),
            totp_secret: None,
        });

        let engine = AuthScriptEngine::new(registry, vault, AuthEngineConfig::default());
        let result = engine
            .continue_authenticate(
                "example.com",
                AuthContinuationInput {
                    kind: ScriptInputKind::TotpCode,
                    value: "654321".to_string(),
                    state: Some("otp-challenge-1".to_string()),
                },
            )
            .await
            .expect("auth");
        assert!(result.success);

        let captured = std::fs::read_to_string(&sidecar).expect("read sidecar");
        let input: serde_json::Value =
            serde_json::from_str(&captured).expect("parse captured input");
        assert_eq!(input["continuation"]["kind"], "totp_code");
        assert_eq!(input["continuation"]["value"], "654321");
        assert_eq!(input["continuation"]["state"], "otp-challenge-1");
    }

    #[tokio::test]
    async fn authenticate_with_totp() {
        let dir = tempfile::tempdir().expect("tempdir");
        let (script, sidecar) = create_stdin_capture_script(dir.path());

        let mut registry = ScriptRegistry::empty();
        registry.register("example.com", script);

        let vault = Arc::new(MockVault::new());
        vault.insert(CredentialRecord {
            service: "example.com".to_string(),
            username: "testuser".to_string(),
            secret: "testpass".to_string(),
            // "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ" = base32 of "12345678901234567890"
            totp_secret: Some("GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ".to_string()),
        });

        let engine = AuthScriptEngine::new(registry, vault, AuthEngineConfig::default());
        let result = engine.authenticate("example.com").await.expect("auth");
        assert!(result.success);

        // Read the captured stdin from the sidecar file
        let captured = std::fs::read_to_string(&sidecar).expect("read sidecar");
        let input: serde_json::Value =
            serde_json::from_str(&captured).expect("parse captured input");
        let totp_code = input["totp_code"].as_str().expect("totp_code present");
        // TOTP code should be exactly 6 digits
        assert_eq!(totp_code.len(), 6);
        assert!(totp_code.chars().all(|c| c.is_ascii_digit()));
    }

    #[tokio::test]
    async fn typescript_extension_spawns_via_npx() {
        // Verify that .ts files are detected for npx ts-node execution.
        // The engine will try `npx ts-node --esm mock.ts` which will fail
        // because the .ts file is not valid TypeScript that produces JSON.
        let dir = tempfile::tempdir().expect("tempdir");
        let script_path = dir.path().join("mock.ts");
        std::fs::write(&script_path, "// typescript file").expect("write");

        let mut registry = ScriptRegistry::empty();
        registry.register("example.com", script_path);

        let vault = Arc::new(MockVault::new());
        vault.insert(CredentialRecord {
            service: "example.com".to_string(),
            username: "user".to_string(),
            secret: "pass".to_string(),
            totp_secret: None,
        });

        let engine = AuthScriptEngine::new(registry, vault, AuthEngineConfig::default());
        let err = engine.authenticate("example.com").await.unwrap_err();
        // Should fail — either ScriptFailed (npx not found / crash) or
        // InvalidOutput (npx ran but script produced no valid JSON).
        assert!(
            matches!(
                err,
                AuthEngineError::ScriptFailed(_) | AuthEngineError::InvalidOutput(_)
            ),
            "expected ScriptFailed or InvalidOutput, got: {err}"
        );
    }

    #[tokio::test]
    async fn scripts_dir_sets_working_directory() {
        // Verify that scripts_dir config is used as current_dir.
        let dir = tempfile::tempdir().expect("tempdir");
        let script = create_success_script(dir.path());

        let mut registry = ScriptRegistry::empty();
        registry.register("example.com", script);

        let vault = Arc::new(MockVault::new());
        vault.insert(CredentialRecord {
            service: "example.com".to_string(),
            username: "user".to_string(),
            secret: "pass".to_string(),
            totp_secret: None,
        });

        let config = AuthEngineConfig {
            scripts_dir: Some(dir.path().to_path_buf()),
            ..AuthEngineConfig::default()
        };
        let engine = AuthScriptEngine::new(registry, vault, config);
        let result = engine.authenticate("example.com").await.expect("auth");
        assert!(result.success);
    }

    #[tokio::test]
    async fn authenticate_uses_fallback_script() {
        let dir = tempfile::tempdir().expect("tempdir");
        let script = create_success_script(dir.path());

        let mut registry = ScriptRegistry::empty();
        registry.set_fallback(script);
        // No domain-specific script for "example.com"

        let vault = Arc::new(MockVault::new());
        vault.insert(CredentialRecord {
            service: "example.com".to_string(),
            username: "user".to_string(),
            secret: "pass".to_string(),
            totp_secret: None,
        });

        let engine = AuthScriptEngine::new(registry, vault, AuthEngineConfig::default());
        let result = engine.authenticate("example.com").await.expect("auth");
        assert!(result.success);
        let attestation = result.attestation.expect("attestation should be present");
        assert_eq!(attestation.profile_id, "_generic");
        assert_eq!(attestation.match_kind, AuthProfileMatchKind::Generic);
    }

    #[tokio::test]
    async fn authenticate_attests_parent_domain_resolution() {
        let dir = tempfile::tempdir().expect("tempdir");
        let script = create_success_script(dir.path());

        let mut registry = ScriptRegistry::empty();
        registry.register("example.com", script);

        let vault = Arc::new(MockVault::new());
        vault.insert(CredentialRecord {
            service: "api.example.com".to_string(),
            username: "user".to_string(),
            secret: "pass".to_string(),
            totp_secret: None,
        });

        let engine = AuthScriptEngine::new(registry, vault, AuthEngineConfig::default());
        let result = engine
            .authenticate("api.example.com")
            .await
            .expect("auth should succeed");
        let attestation = result.attestation.expect("attestation should be present");
        assert_eq!(attestation.requested_domain, "api.example.com");
        assert_eq!(attestation.profile_id, "example.com");
        assert_eq!(attestation.match_kind, AuthProfileMatchKind::Parent);
    }
}
