#!/usr/bin/env bash
# bootstrap-vps.sh - Staged VPS bootstrap with preflight gates, rollback, and firewall hardening.
#
# Architecture contract: docs/architecture/vps-deployment.md (lines 203-216)
#
# Stages:
#   1. Preflight   - verify OS, disk, network, dependencies
#   2. Firewall    - harden ufw (deny-all baseline + mode-specific ingress)
#   3. Config      - deploy config files + validate checksums
#   4. Services    - build, pull images, start compose, health-check, room setup
#
# Flags:
#   --dry-run       Print what would happen without making changes
#   --force-reset   Destroy volumes and recreate (WARNING: destroys vault data)
#   --skip-firewall Skip ufw configuration (for environments where it's managed externally)
#   --skip-ssh-hardening Skip sshd hardening (not recommended)
#   --access-mode   Access mode: "public" (default) or "tailnet"
#   --public-domain Public Matrix domain (for public mode, can also come from config/.env.runtime)
#   Public mode also requires SYMBIOTIC_CLOUDFLARE_TUNNEL_TOKEN in config/.env.secrets or environment.
#   --matrix-password-file Path to one-line matrix app password generated by installer/app
#
# Idempotency: re-running is safe. Existing volumes are preserved unless --force-reset.

set -euo pipefail

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_FILE="$ROOT_DIR/docker-compose.vps.yml"
CONFIG_DIR="$ROOT_DIR/config"
ROLLBACK_DIR="$ROOT_DIR/.bootstrap-rollback"
STAGE_MARKER_DIR="$ROOT_DIR/.bootstrap-stages"
LOG_FILE="$ROOT_DIR/.bootstrap.log"

REQUIRED_DISK_MB=2048          # 2 GB minimum free
HEALTH_CHECK_TIMEOUT_S=60      # seconds to wait for container health
HEALTH_CHECK_INTERVAL_S=5

# Tailscale interface names (checked in order)
TS_INTERFACES=("tailscale0" "utun" "ts")

# Services that must be healthy before room/bootstrap setup
BASE_SERVICES=("conduwuit")

# ---------------------------------------------------------------------------
# Globals
# ---------------------------------------------------------------------------
DRY_RUN=false
FORCE_RESET=false
SKIP_FIREWALL=false
SKIP_SSH_HARDENING=false
ACCESS_MODE="public"
PUBLIC_DOMAIN=""
MATRIX_PASSWORD_FILE=""
CLOUDFLARE_TUNNEL_TOKEN=""
CURRENT_STAGE=0
COMPOSE_ARGS=()

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
log() {
  local level="$1"; shift
  local msg
  msg="[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] [$level] $*"
  echo "$msg" | tee -a "$LOG_FILE"
}

info()  { log "INFO"  "$@"; }
warn()  { log "WARN"  "$@"; }
error() { log "ERROR" "$@"; }

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --dry-run)       DRY_RUN=true ;;
      --force-reset)   FORCE_RESET=true ;;
      --skip-firewall) SKIP_FIREWALL=true ;;
      --skip-ssh-hardening) SKIP_SSH_HARDENING=true ;;
      --access-mode)
        shift
        ACCESS_MODE="${1:-}"
        ;;
      --public-domain)
        shift
        PUBLIC_DOMAIN="${1:-}"
        ;;
      --matrix-password-file)
        shift
        MATRIX_PASSWORD_FILE="${1:-}"
        ;;
      -h|--help)       usage; exit 0 ;;
      *)               error "Unknown flag: $1"; usage; exit 1 ;;
    esac
    shift
  done

  case "$ACCESS_MODE" in
    public|tailnet|caddy) ;;
    *)
      error "Invalid --access-mode: $ACCESS_MODE (expected: public|tailnet|caddy)"
      usage
      exit 1
      ;;
  esac

  COMPOSE_ARGS=("-f" "$COMPOSE_FILE")
  if [[ "$ACCESS_MODE" == "public" ]]; then
    COMPOSE_ARGS+=("--profile" "public")
  elif [[ "$ACCESS_MODE" == "caddy" ]]; then
    COMPOSE_ARGS+=("--profile" "caddy")
  fi
}

usage() {
  cat <<'EOF'
Usage: bootstrap-vps.sh [OPTIONS]

Options:
  --dry-run         Print actions without executing
  --force-reset     Destroy volumes and recreate (DESTROYS vault data)
  --skip-firewall   Skip ufw configuration
  --skip-ssh-hardening Skip SSH hardening (not recommended)
  --access-mode     Access mode: public (default), tailnet, or caddy
  --public-domain   Public Matrix domain (required for public/caddy mode unless set in config/.env.runtime)
                    Public mode also requires SYMBIOTIC_CLOUDFLARE_TUNNEL_TOKEN
  --matrix-password-file Path to one-line Matrix app password generated by installer/app
  -h, --help        Show this help
EOF
}

# ---------------------------------------------------------------------------
# Dry-run wrapper: only execute if not in dry-run mode
# ---------------------------------------------------------------------------
run() {
  if $DRY_RUN; then
    info "[dry-run] $*"
    return 0
  fi
  "$@"
}

generate_hex() {
  local bytes="${1:-32}"
  head -c "$bytes" /dev/urandom | xxd -p -c 256 | tr -d '\n'
}

validate_matrix_password() {
  local password="$1"
  if [[ -z "$password" ]]; then
    error "Provided matrix password is empty"
    return 1
  fi
  if [[ "$password" =~ [[:space:]] ]]; then
    error "Provided matrix password contains whitespace; use a single-line value"
    return 1
  fi
  if [[ "${#password}" -lt 16 ]]; then
    error "Provided matrix password is too short (need at least 16 chars)"
    return 1
  fi
}

resolve_public_domain() {
  # CLI flag takes precedence.
  if [[ -n "$PUBLIC_DOMAIN" ]]; then
    return 0
  fi

  local runtime_env="$CONFIG_DIR/.env.runtime"
  if [[ -f "$runtime_env" ]]; then
    # shellcheck disable=SC1090
    source "$runtime_env"
    PUBLIC_DOMAIN="${SYMBIOTIC_MATRIX_PUBLIC_DOMAIN:-}"
  fi
}

read_env_key_from_file() {
  local file="$1"
  local key="$2"
  if [[ ! -f "$file" ]]; then
    return 0
  fi
  sed -n "s/^${key}=//p" "$file" | tail -n1 | tr -d '\r\n'
}

resolve_cloudflare_tunnel_token() {
  if [[ -n "${SYMBIOTIC_CLOUDFLARE_TUNNEL_TOKEN:-}" ]]; then
    CLOUDFLARE_TUNNEL_TOKEN="${SYMBIOTIC_CLOUDFLARE_TUNNEL_TOKEN}"
    return 0
  fi
  CLOUDFLARE_TUNNEL_TOKEN="$(read_env_key_from_file "$CONFIG_DIR/.env.secrets" "SYMBIOTIC_CLOUDFLARE_TUNNEL_TOKEN")"
}

# ---------------------------------------------------------------------------
# Stage markers (for rollback tracking)
# ---------------------------------------------------------------------------
mark_stage_start() {
  local stage="$1"
  CURRENT_STAGE="$stage"
  mkdir -p "$STAGE_MARKER_DIR"
  echo "started $(date -u '+%Y-%m-%dT%H:%M:%SZ')" > "$STAGE_MARKER_DIR/stage-$stage"
  info "--- Stage $stage started ---"
}

mark_stage_done() {
  local stage="$1"
  echo "done $(date -u '+%Y-%m-%dT%H:%M:%SZ')" > "$STAGE_MARKER_DIR/stage-$stage"
  info "--- Stage $stage completed ---"
}

stage_is_done() {
  local stage="$1"
  [[ -f "$STAGE_MARKER_DIR/stage-$stage" ]] && grep -q "^done" "$STAGE_MARKER_DIR/stage-$stage"
}

clear_stage_markers() {
  rm -rf "$STAGE_MARKER_DIR"
}

# ---------------------------------------------------------------------------
# Rollback
# ---------------------------------------------------------------------------
save_rollback_snapshot() {
  if $DRY_RUN; then
    info "[dry-run] Would save rollback snapshot"
    return 0
  fi
  mkdir -p "$ROLLBACK_DIR"
  # Save current compose file if it exists on the target
  if [[ -f "$COMPOSE_FILE" ]]; then
    cp "$COMPOSE_FILE" "$ROLLBACK_DIR/docker-compose.vps.yml.prev"
  fi
  # Save config checksums
  if [[ -d "$CONFIG_DIR" ]]; then
    find "$CONFIG_DIR" -type f -exec sha256sum {} \; > "$ROLLBACK_DIR/config-checksums.prev" 2>/dev/null || true
  fi
  info "Rollback snapshot saved to $ROLLBACK_DIR"
}

rollback() {
  error "Bootstrap failed at stage $CURRENT_STAGE. Rolling back..."

  if $DRY_RUN; then
    info "[dry-run] Would roll back stages 1..$CURRENT_STAGE"
    return 0
  fi

  # Stage 4 rollback: restore previous compose if available
  if [[ "$CURRENT_STAGE" -ge 4 ]] && [[ -f "$ROLLBACK_DIR/docker-compose.vps.yml.prev" ]]; then
    warn "Restoring previous compose file and restarting services..."
    cp "$ROLLBACK_DIR/docker-compose.vps.yml.prev" "$COMPOSE_FILE"
    docker compose "${COMPOSE_ARGS[@]}" up -d 2>/dev/null || true
  fi

  # Stage 3 rollback: config files are non-destructive (compose volumes untouched)
  # No action needed -- old compose already restored above if stage 4 was attempted.

  # Stage 2 rollback: we don't remove firewall rules on failure (safer to leave locked down)
  if [[ "$CURRENT_STAGE" -ge 2 ]]; then
    warn "Firewall rules were applied and will NOT be rolled back (fail-closed)."
  fi

  # Stage 1 is read-only (preflight), nothing to roll back.
  error "Rollback complete. Review $LOG_FILE for details."
}

# Trap for unexpected failures
trap 'rollback' ERR

# ---------------------------------------------------------------------------
# Stage 1: Preflight gates
# ---------------------------------------------------------------------------
check_os() {
  info "Checking OS..."
  if [[ "$(uname -s)" != "Linux" ]]; then
    # Allow dry-run on non-Linux for testing
    if $DRY_RUN; then
      warn "Not Linux ($(uname -s)) -- dry-run allows this"
      return 0
    fi
    error "VPS bootstrap requires Linux (detected: $(uname -s))"
    return 1
  fi
  info "OS: Linux ($(uname -r))"
}

check_disk() {
  info "Checking disk space..."
  local free_mb
  if [[ "$(uname -s)" == "Linux" ]]; then
    free_mb=$(df --output=avail -m / | tail -1 | tr -d ' ')
  else
    # macOS fallback for dry-run
    free_mb=$(df -m / | tail -1 | awk '{print $4}')
  fi

  if [[ "$free_mb" -lt "$REQUIRED_DISK_MB" ]]; then
    error "Insufficient disk space: ${free_mb}MB free, need ${REQUIRED_DISK_MB}MB"
    return 1
  fi
  info "Disk space: ${free_mb}MB free (minimum: ${REQUIRED_DISK_MB}MB)"
}

check_dependencies() {
  info "Checking required binaries..."
  local missing=()

  if ! command -v docker >/dev/null 2>&1; then
    if $DRY_RUN; then
      warn "[dry-run] docker missing -- would install Docker Engine + compose plugin"
    else
      info "docker not found. Installing Docker Engine + compose plugin..."
      apt-get update -qq
      apt-get install -y -qq ca-certificates curl
      curl -fsSL https://get.docker.com | sh
      systemctl enable --now docker >/dev/null 2>&1 || true
    fi
  fi

  if [[ "$ACCESS_MODE" == "tailnet" ]] && ! command -v tailscale >/dev/null 2>&1; then
    if $DRY_RUN; then
      warn "[dry-run] tailscale missing -- would install tailscale"
    else
      info "tailscale not found. Installing tailscale..."
      curl -fsSL https://tailscale.com/install.sh | sh
      systemctl enable --now tailscaled >/dev/null 2>&1 || true
    fi
  fi

  local required_bins=("docker")
  if [[ "$ACCESS_MODE" == "tailnet" ]]; then
    required_bins+=("tailscale")
  fi

  for bin in "${required_bins[@]}"; do
    if ! command -v "$bin" >/dev/null 2>&1; then
      missing+=("$bin")
    fi
  done

  if [[ ${#missing[@]} -gt 0 ]]; then
    if $DRY_RUN; then
      warn "[dry-run] Missing binaries: ${missing[*]} -- would fail in real run"
    else
      error "Missing required binaries: ${missing[*]}"
      error "Install them first: docker (https://docs.docker.com/engine/install/)"
      if [[ "$ACCESS_MODE" == "tailnet" ]]; then
        error "Tailscale required for tailnet mode: https://tailscale.com/download"
      fi
      return 1
    fi
  fi

  # Check docker compose plugin
  if ! docker compose version >/dev/null 2>&1; then
    if $DRY_RUN; then
      warn "[dry-run] 'docker compose' plugin not available -- would fail in real run"
    else
      error "'docker compose' plugin not available. Install docker-compose-plugin."
      return 1
    fi
  fi

  if [[ "$ACCESS_MODE" == "tailnet" ]]; then
    info "Dependencies checked: docker, tailscale, docker compose"
  else
    info "Dependencies checked: docker, docker compose"
  fi
}

check_network() {
  if [[ "$ACCESS_MODE" != "tailnet" ]]; then
    info "Skipping Tailscale connectivity check (access mode: public)"
    return 0
  fi

  info "Checking Tailscale connectivity..."

  # Check if tailscale is running
  if ! tailscale status >/dev/null 2>&1; then
    if $DRY_RUN; then
      warn "[dry-run] Tailscale not running -- skipping network check"
      return 0
    fi
    error "Tailscale is not running. Start it with: sudo tailscale up"
    return 1
  fi

  # Verify tailscale has an IP (i.e., is connected to the mesh)
  local ts_ip
  ts_ip=$(tailscale ip -4 2>/dev/null || true)
  if [[ -z "$ts_ip" ]]; then
    if $DRY_RUN; then
      warn "[dry-run] No Tailscale IP -- skipping"
      return 0
    fi
    error "Tailscale has no IPv4 address. Authenticate with: sudo tailscale up"
    return 1
  fi

  info "Tailscale connected: $ts_ip"
}

check_public_config() {
  if [[ "$ACCESS_MODE" != "public" ]] && [[ "$ACCESS_MODE" != "caddy" ]]; then
    return 0
  fi

  resolve_public_domain

  if [[ -z "$PUBLIC_DOMAIN" ]]; then
    if $DRY_RUN; then
      warn "[dry-run] No public domain configured. Set SYMBIOTIC_MATRIX_PUBLIC_DOMAIN in config/.env.runtime or pass --public-domain."
      return 0
    fi
    error "$ACCESS_MODE mode requires a domain. Set SYMBIOTIC_MATRIX_PUBLIC_DOMAIN in config/.env.runtime or pass --public-domain."
    return 1
  fi

  info "Public Matrix domain: $PUBLIC_DOMAIN"

  # Caddy mode uses Let's Encrypt — no tunnel token needed.
  if [[ "$ACCESS_MODE" == "caddy" ]]; then
    return 0
  fi

  # Public mode requires Cloudflare tunnel token.
  resolve_cloudflare_tunnel_token

  if [[ -z "$CLOUDFLARE_TUNNEL_TOKEN" ]]; then
    if $DRY_RUN; then
      warn "[dry-run] SYMBIOTIC_CLOUDFLARE_TUNNEL_TOKEN is missing. Public mode requires a Cloudflare tunnel token."
      return 0
    fi
    error "Public mode requires SYMBIOTIC_CLOUDFLARE_TUNNEL_TOKEN (set in config/.env.secrets or environment)."
    return 1
  fi

  info "Cloudflare tunnel token: configured"
}

check_compose_file() {
  info "Checking compose file..."
  if [[ ! -f "$COMPOSE_FILE" ]]; then
    error "Compose file not found: $COMPOSE_FILE"
    return 1
  fi
  info "Compose file present: $COMPOSE_FILE"
}

run_preflight() {
  mark_stage_start 1
  info "=== Stage 1: Preflight Gates ==="

  check_os
  check_disk
  check_dependencies
  check_network
  check_public_config
  check_compose_file

  mark_stage_done 1
}

# ---------------------------------------------------------------------------
# Stage 2: Firewall hardening
# ---------------------------------------------------------------------------
detect_tailscale_interface() {
  for iface in "${TS_INTERFACES[@]}"; do
    if ip link show "$iface" >/dev/null 2>&1; then
      echo "$iface"
      return 0
    fi
  done
  # Fallback: search for tailscale in ip link output
  ip link show 2>/dev/null | grep -oP '(?<=: )(tailscale\S*|utun\S*)' | head -1 || true
}

configure_firewall() {
  mark_stage_start 2

  if $SKIP_FIREWALL; then
    info "=== Stage 2: Firewall (skipped via --skip-firewall) ==="
    mark_stage_done 2
    return 0
  fi

  info "=== Stage 2: Firewall Hardening ==="

  # Check if ufw is available
  if ! command -v ufw >/dev/null 2>&1; then
    if $DRY_RUN; then
      info "[dry-run] ufw not installed -- would install"
    else
      warn "ufw not installed. Installing..."
      apt-get update -qq && apt-get install -y -qq ufw
    fi
  fi

  local ts_iface=""
  if command -v tailscale >/dev/null 2>&1; then
    ts_iface=$(detect_tailscale_interface)
  fi

  # Apply firewall rules (idempotent -- ufw handles duplicates gracefully)
  run ufw --force reset

  # Default deny all
  run ufw default deny incoming
  run ufw default deny outgoing

  # Allow all traffic on Tailscale interface (VPN mesh) when present.
  if [[ -n "$ts_iface" ]]; then
    info "Tailscale interface: $ts_iface"
    run ufw allow in on "$ts_iface"
    run ufw allow out on "$ts_iface"
  elif [[ "$ACCESS_MODE" == "tailnet" ]]; then
    if $DRY_RUN; then
      warn "[dry-run] Could not detect Tailscale interface. Would use tailscale0."
      run ufw allow in on tailscale0
      run ufw allow out on tailscale0
    else
      error "Tailnet mode selected but Tailscale interface was not detected."
      return 1
    fi
  fi

  # SSH ingress for all public-facing modes.
  if [[ "$ACCESS_MODE" == "public" ]] || [[ "$ACCESS_MODE" == "caddy" ]]; then
    run ufw allow 22/tcp
  fi

  # Caddy mode: ports 80 (HTTP challenge) and 443 (HTTPS) must be open.
  if [[ "$ACCESS_MODE" == "caddy" ]]; then
    run ufw allow 80/tcp
    run ufw allow 443/tcp
  fi

  # Allow outbound for package management and container pulls
  run ufw allow out 53    # DNS
  run ufw allow out 443   # HTTPS (container registry, Tailscale coordination)
  run ufw allow out 80    # HTTP (package repos)

  # Allow Docker internal networking (bridge traffic)
  run ufw allow in on docker0
  run ufw allow out on docker0

  # Allow loopback
  run ufw allow in on lo
  run ufw allow out on lo

  # Enable firewall
  run ufw --force enable

  if [[ "$ACCESS_MODE" == "caddy" ]]; then
    info "Firewall rules applied: deny-all + SSH + HTTP/HTTPS ingress + Docker + DNS/HTTPS egress"
  elif [[ "$ACCESS_MODE" == "public" ]]; then
    info "Firewall rules applied: deny-all + SSH + Docker + DNS/HTTPS egress"
  else
    info "Firewall rules applied: deny-all + Tailscale + Docker + DNS/HTTPS egress"
  fi
  mark_stage_done 2
}

# ---------------------------------------------------------------------------
# Stage 3: Config deployment + checksum validation
# ---------------------------------------------------------------------------
deploy_config() {
  mark_stage_start 3
  info "=== Stage 3: Config Deployment ==="

  # Ensure config directory exists
  if [[ ! -d "$CONFIG_DIR" ]]; then
    warn "Config directory not found at $CONFIG_DIR -- creating scaffold"
    run mkdir -p "$CONFIG_DIR"
  fi

  # Create .env.runtime if missing (scaffold with safe defaults)
  if [[ ! -f "$CONFIG_DIR/.env.runtime" ]]; then
    info "Creating scaffold .env.runtime"
    if ! $DRY_RUN; then
      cat > "$CONFIG_DIR/.env.runtime" <<'ENVEOF'
# Symbiotic VPS runtime configuration (non-secret)
# Generated by bootstrap-vps.sh -- edit as needed
SYMBIOTIC_MATRIX_HOMESERVER=http://conduwuit:8008
SYMBIOTIC_MATRIX_USER=testuser
SYMBIOTIC_ALLOWED_SENDERS=@testuser:symbiotic.local
SYMBIOTIC_ALLOW_OPEN_ACCESS=false
SYMBIOTIC_LOG_LEVEL=info
# Public mode domain (required for app access without Tailscale)
#SYMBIOTIC_MATRIX_PUBLIC_DOMAIN=matrix.example.com
ENVEOF
    fi
  fi

  # Persist public domain into runtime config when provided.
  if [[ "$ACCESS_MODE" == "public" ]] || [[ "$ACCESS_MODE" == "caddy" ]]; then
    resolve_public_domain
    if [[ -n "$PUBLIC_DOMAIN" ]] && [[ -f "$CONFIG_DIR/.env.runtime" ]] && ! $DRY_RUN; then
      local runtime_file="$CONFIG_DIR/.env.runtime"
      if grep -q '^SYMBIOTIC_MATRIX_PUBLIC_DOMAIN=' "$runtime_file"; then
        sed -i.bak "s|^SYMBIOTIC_MATRIX_PUBLIC_DOMAIN=.*|SYMBIOTIC_MATRIX_PUBLIC_DOMAIN=${PUBLIC_DOMAIN}|" "$runtime_file"
        rm -f "${runtime_file}.bak"
      else
        printf "\nSYMBIOTIC_MATRIX_PUBLIC_DOMAIN=%s\n" "$PUBLIC_DOMAIN" >> "$runtime_file"
      fi
    fi
  fi

  # Create .env.secrets if missing (generate random vault master key)
  if [[ ! -f "$CONFIG_DIR/.env.secrets" ]]; then
    info "Creating .env.secrets with generated VAULT_MASTER_KEY"
    if ! $DRY_RUN; then
      local vault_key
      vault_key=$(generate_hex 32)
      cat > "$CONFIG_DIR/.env.secrets" <<ENVEOF
# Symbiotic VPS secrets -- NEVER commit this file
# Generated by bootstrap-vps.sh
SYMBIOTIC_VAULT_MASTER_KEY=${vault_key}
# MATRIX_ADMIN_TOKEN=
ENVEOF
      chmod 600 "$CONFIG_DIR/.env.secrets"
    fi
  fi

  # Ensure env secrets file does not carry plaintext Matrix password.
  # Matrix auth comes from Docker secret/vault bootstrap, not env vars.
  if [[ -f "$CONFIG_DIR/.env.secrets" ]] && ! $DRY_RUN; then
    if grep -q '^SYMBIOTIC_MATRIX_PASSWORD=' "$CONFIG_DIR/.env.secrets"; then
      warn "Removing deprecated SYMBIOTIC_MATRIX_PASSWORD from config/.env.secrets"
      sed -i.bak '/^SYMBIOTIC_MATRIX_PASSWORD=/d' "$CONFIG_DIR/.env.secrets"
      rm -f "$CONFIG_DIR/.env.secrets.bak"
    fi

    # Backward-compat: migrate legacy VAULT_MASTER_KEY -> SYMBIOTIC_VAULT_MASTER_KEY
    if grep -q '^VAULT_MASTER_KEY=' "$CONFIG_DIR/.env.secrets" \
      && ! grep -q '^SYMBIOTIC_VAULT_MASTER_KEY=' "$CONFIG_DIR/.env.secrets"; then
      local legacy_vault_key
      legacy_vault_key=$(sed -n 's/^VAULT_MASTER_KEY=//p' "$CONFIG_DIR/.env.secrets" | head -n1 | tr -d '\r\n')
      if [[ -n "$legacy_vault_key" ]]; then
        printf "\nSYMBIOTIC_VAULT_MASTER_KEY=%s\n" "$legacy_vault_key" >> "$CONFIG_DIR/.env.secrets"
      fi
    fi
  fi

  # Ensure Cloudflare tunnel token is persisted for public mode bootstrap.
  if [[ "$ACCESS_MODE" == "public" ]] && [[ -f "$CONFIG_DIR/.env.secrets" ]]; then
    resolve_cloudflare_tunnel_token
    if [[ -n "$CLOUDFLARE_TUNNEL_TOKEN" ]] && ! $DRY_RUN; then
      if grep -q '^SYMBIOTIC_CLOUDFLARE_TUNNEL_TOKEN=' "$CONFIG_DIR/.env.secrets"; then
        sed -i.bak "s|^SYMBIOTIC_CLOUDFLARE_TUNNEL_TOKEN=.*|SYMBIOTIC_CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}|" "$CONFIG_DIR/.env.secrets"
        rm -f "$CONFIG_DIR/.env.secrets.bak"
      else
        printf "\nSYMBIOTIC_CLOUDFLARE_TUNNEL_TOKEN=%s\n" "$CLOUDFLARE_TUNNEL_TOKEN" >> "$CONFIG_DIR/.env.secrets"
      fi
    fi
  fi

  # Ensure Docker secret for Matrix password exists.
  # This secret is required by docker-compose.vps.yml.
  local matrix_secret_dir="$CONFIG_DIR/.secrets"
  local matrix_secret_file="$matrix_secret_dir/matrix_password"
  local matrix_password_record="$CONFIG_DIR/.matrix-passwords"
  local bootstrap_matrix_password=""
  if [[ -n "$MATRIX_PASSWORD_FILE" ]]; then
    if [[ ! -f "$MATRIX_PASSWORD_FILE" ]]; then
      error "Matrix password file not found: $MATRIX_PASSWORD_FILE"
      return 1
    fi
    bootstrap_matrix_password=$(tr -d '\r\n' < "$MATRIX_PASSWORD_FILE")
    validate_matrix_password "$bootstrap_matrix_password"
  fi
  if ! $DRY_RUN; then
    local matrix_password=""
    if [[ -f "$matrix_secret_file" ]]; then
      matrix_password=$(tr -d '\r\n' < "$matrix_secret_file")
    fi

    # Backward-compat: recover from local password record if secret file is missing.
    if [[ -z "$matrix_password" ]] && [[ -f "$matrix_password_record" ]]; then
      matrix_password=$(sed -n 's/^MATRIX_TESTUSER_PASSWORD=//p' "$matrix_password_record" | head -n1 | tr -d '\r\n')
      if [[ -z "$matrix_password" ]]; then
        matrix_password=$(sed -n 's/^MATRIX_DAEMON_PASSWORD=//p' "$matrix_password_record" | head -n1 | tr -d '\r\n')
      fi
    fi

    if [[ -n "$bootstrap_matrix_password" ]]; then
      matrix_password="$bootstrap_matrix_password"
      info "Using Matrix password from installer-supplied file"
    elif [[ -z "$matrix_password" ]]; then
      info "Creating Matrix Docker secret: $matrix_secret_file"
      matrix_password=$(generate_hex 32)
    else
      info "Using existing Matrix password state"
    fi

    mkdir -p "$matrix_secret_dir"
    printf "%s\n" "$matrix_password" > "$matrix_secret_file"
    # Docker Compose file-based secrets are bind-mounted as-is in this setup.
    # Use 0644 so the non-root daemon user can read /run/secrets/... in-container.
    chmod 644 "$matrix_secret_file"

    # Save operator-readable record for app login bootstrap (single source mirror).
    cat > "$matrix_password_record" <<EOF
# Generated by bootstrap-vps.sh
MATRIX_TESTUSER_PASSWORD=${matrix_password}
MATRIX_DAEMON_PASSWORD=${matrix_password}
EOF
    chmod 600 "$matrix_password_record"
  fi

  # Validate config checksums (informational -- not blocking on first run)
  if [[ -f "$ROLLBACK_DIR/config-checksums.prev" ]]; then
    info "Validating config checksums against previous run..."
    local changed=0
    while IFS= read -r line; do
      local checksum file
      checksum=$(echo "$line" | awk '{print $1}')
      file=$(echo "$line" | awk '{print $2}')
      if [[ -f "$file" ]]; then
        local current
        current=$(sha256sum "$file" 2>/dev/null | awk '{print $1}')
        if [[ "$current" != "$checksum" ]]; then
          info "Config changed: $file"
          changed=$((changed + 1))
        fi
      fi
    done < "$ROLLBACK_DIR/config-checksums.prev"
    info "Config files changed since last run: $changed"
  else
    info "No previous config checksums (first run)"
  fi

  mark_stage_done 3
}

# ---------------------------------------------------------------------------
# Stage 4: Service deployment + health checks
# ---------------------------------------------------------------------------
deploy_services() {
  mark_stage_start 4
  info "=== Stage 4: Service Deployment ==="

  local base_services=("${BASE_SERVICES[@]}")
  if [[ "$ACCESS_MODE" == "public" ]]; then
    base_services+=("matrix-gateway")
  elif [[ "$ACCESS_MODE" == "caddy" ]]; then
    base_services+=("caddy")
  fi
  local expected_services=("${base_services[@]}" "daemon")

  # Handle --force-reset
  if $FORCE_RESET; then
    warn "--force-reset: destroying volumes and recreating (vault data will be lost!)"
    run docker compose "${COMPOSE_ARGS[@]}" down -v
  fi

  # Build daemon image from Dockerfile
  info "Building daemon image..."
  run docker compose "${COMPOSE_ARGS[@]}" build

  # Pull images (allow failure for offline/pre-cached scenarios)
  info "Pulling container images..."
  run docker compose "${COMPOSE_ARGS[@]}" pull || {
    warn "Image pull failed or partially failed -- continuing with cached images"
  }

  # Start base services first (Conduwuit + optional gateway).
  info "Starting base services: ${base_services[*]}"
  run docker compose "${COMPOSE_ARGS[@]}" up -d "${base_services[@]}"

  if $DRY_RUN; then
    info "[dry-run] Would wait for base services, run room setup, then start daemon"
    mark_stage_done 4
    return 0
  fi

  # Wait for base services first.
  info "Waiting for base services (timeout: ${HEALTH_CHECK_TIMEOUT_S}s)..."
  local elapsed=0
  local all_healthy=false

  while [[ "$elapsed" -lt "$HEALTH_CHECK_TIMEOUT_S" ]]; do
    all_healthy=true
    for svc in "${base_services[@]}"; do
      local state
      state=$(docker compose "${COMPOSE_ARGS[@]}" ps --format '{{.State}}' "$svc" 2>/dev/null || echo "missing")
      if [[ "$state" != "running" ]]; then
        all_healthy=false
        break
      fi
    done

    if $all_healthy; then
      break
    fi

    sleep "$HEALTH_CHECK_INTERVAL_S"
    elapsed=$((elapsed + HEALTH_CHECK_INTERVAL_S))
  done

  if ! $all_healthy; then
    error "Base services not healthy after ${HEALTH_CHECK_TIMEOUT_S}s"
    error "Service status:"
    docker compose "${COMPOSE_ARGS[@]}" ps 2>/dev/null || true
    return 1
  fi

  info "Base services running"

  # Set up Matrix rooms and users
  local room_setup_script="$ROOT_DIR/scripts/setup-matrix-rooms.sh"
  if [[ -x "$room_setup_script" ]]; then
    info "Running Matrix room setup..."
    local room_setup_homeserver="http://127.0.0.1:8008"
    local room_setup_extra_flags=()
    local room_flags=()
    if $DRY_RUN; then
      room_flags+=("--dry-run")
    fi
    if ! "$room_setup_script" --homeserver "$room_setup_homeserver" "${room_setup_extra_flags[@]}" "${room_flags[@]}"; then
      if [[ "$ACCESS_MODE" == "public" ]]; then
        warn "Room setup probe from host failed in public mode; continuing."
        warn "Daemon bootstrap will create/login user and ensure rooms from inside Docker network."
      else
        error "Room setup failed"
        return 1
      fi
    fi
  else
    error "Room setup script not found at $room_setup_script"
    return 1
  fi

  # Start daemon only after Matrix user + rooms are guaranteed.
  info "Starting daemon..."
  run docker compose "${COMPOSE_ARGS[@]}" up -d daemon

  # Final health check: all expected services including daemon.
  info "Waiting for all services (timeout: ${HEALTH_CHECK_TIMEOUT_S}s)..."
  elapsed=0
  all_healthy=false
  while [[ "$elapsed" -lt "$HEALTH_CHECK_TIMEOUT_S" ]]; do
    all_healthy=true
    for svc in "${expected_services[@]}"; do
      local state
      state=$(docker compose "${COMPOSE_ARGS[@]}" ps --format '{{.State}}' "$svc" 2>/dev/null || echo "missing")
      if [[ "$state" != "running" ]]; then
        all_healthy=false
        break
      fi
    done

    if $all_healthy; then
      break
    fi

    sleep "$HEALTH_CHECK_INTERVAL_S"
    elapsed=$((elapsed + HEALTH_CHECK_INTERVAL_S))
  done

  if ! $all_healthy; then
    error "Not all services healthy after ${HEALTH_CHECK_TIMEOUT_S}s"
    error "Service status:"
    docker compose "${COMPOSE_ARGS[@]}" ps 2>/dev/null || true
    return 1
  fi

  if [[ "$ACCESS_MODE" == "tailnet" ]]; then
    configure_tailscale_serve
  fi

  mark_stage_done 4
}

# ---------------------------------------------------------------------------
# Stage 5: SSH hardening
# ---------------------------------------------------------------------------
has_any_ssh_authorized_keys() {
  if [[ -f "/root/.ssh/authorized_keys" ]] \
    && grep -Eq '^\s*(ssh-|ecdsa-|sk-ssh-)' /root/.ssh/authorized_keys; then
    return 0
  fi

  local user_key
  user_key=$(find /home -maxdepth 3 -type f -path "*/.ssh/authorized_keys" -size +0c 2>/dev/null | head -n1 || true)
  [[ -n "$user_key" ]]
}

configure_ssh_hardening() {
  mark_stage_start 5

  if $SKIP_SSH_HARDENING; then
    info "=== Stage 5: SSH hardening (skipped via --skip-ssh-hardening) ==="
    mark_stage_done 5
    return 0
  fi

  info "=== Stage 5: SSH hardening ==="

  if [[ "$(id -u)" -ne 0 ]]; then
    warn "SSH hardening requires root privileges; skipping"
    mark_stage_done 5
    return 0
  fi

  local sshd_bin
  sshd_bin="$(command -v sshd || true)"
  if [[ -z "$sshd_bin" ]] && [[ -x "/usr/sbin/sshd" ]]; then
    sshd_bin="/usr/sbin/sshd"
  fi
  if [[ -z "$sshd_bin" ]]; then
    warn "sshd not found; skipping SSH hardening"
    mark_stage_done 5
    return 0
  fi

  if ! has_any_ssh_authorized_keys; then
    warn "No SSH public keys found in authorized_keys. Skipping password-auth hardening to avoid lockout."
    warn "Add an SSH key first, then re-run bootstrap to apply hardening."
    mark_stage_done 5
    return 0
  fi

  local sshd_dropin_dir="/etc/ssh/sshd_config.d"
  local sshd_dropin_file="${sshd_dropin_dir}/99-symbiotic-hardening.conf"
  local sshd_dropin_backup="${sshd_dropin_file}.bak"
  local sshd_dropin_tmp="${sshd_dropin_file}.tmp"

  if $DRY_RUN; then
    info "[dry-run] Would write ${sshd_dropin_file} and reload sshd"
    mark_stage_done 5
    return 0
  fi

  mkdir -p "$sshd_dropin_dir"
  if [[ -f "$sshd_dropin_file" ]]; then
    cp "$sshd_dropin_file" "$sshd_dropin_backup"
  fi

  cat > "$sshd_dropin_tmp" <<'EOF'
# Managed by scripts/bootstrap-vps.sh
PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
PermitEmptyPasswords no
PubkeyAuthentication yes
PermitRootLogin prohibit-password
MaxAuthTries 3
LoginGraceTime 30
X11Forwarding no
EOF
  mv "$sshd_dropin_tmp" "$sshd_dropin_file"
  chmod 600 "$sshd_dropin_file"

  if ! "$sshd_bin" -t; then
    error "sshd configuration test failed; restoring previous SSH config"
    if [[ -f "$sshd_dropin_backup" ]]; then
      mv "$sshd_dropin_backup" "$sshd_dropin_file"
    else
      rm -f "$sshd_dropin_file"
    fi
    "$sshd_bin" -t >/dev/null 2>&1 || true
    return 1
  fi

  if systemctl list-unit-files | grep -q '^sshd\.service'; then
    systemctl reload sshd || systemctl restart sshd
  elif systemctl list-unit-files | grep -q '^ssh\.service'; then
    systemctl reload ssh || systemctl restart ssh
  else
    warn "Could not identify ssh service unit automatically; reload manually if needed."
  fi

  info "SSH hardening applied: password auth disabled, pubkey auth required"
  mark_stage_done 5
}

# ---------------------------------------------------------------------------
# Expose Matrix to tailnet via Tailscale Serve (best effort)
# ---------------------------------------------------------------------------
configure_tailscale_serve() {
  info "Configuring Tailscale Serve for Matrix access..."

  if ! command -v tailscale >/dev/null 2>&1; then
    warn "tailscale CLI not found; skipping serve configuration"
    return 0
  fi

  if $DRY_RUN; then
    info "[dry-run] Would run: tailscale serve --bg 8008"
    return 0
  fi

  # Newer tailscale versions accept "8008"; older ones may need explicit target.
  if tailscale serve --bg 8008 >/dev/null 2>&1; then
    info "Tailscale Serve configured: 8008"
  elif tailscale serve --bg http://127.0.0.1:8008 >/dev/null 2>&1; then
    info "Tailscale Serve configured: http://127.0.0.1:8008"
  else
    warn "Could not configure Tailscale Serve automatically. Run manually:"
    warn "  sudo tailscale serve --bg 8008"
    return 0
  fi

  tailscale serve status 2>/dev/null | sed 's/^/[tailscale-serve] /' | tee -a "$LOG_FILE" || true
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
  parse_args "$@"

  info "=========================================="
  info "Symbiotic VPS Bootstrap"
  info "=========================================="
  info "Root:        $ROOT_DIR"
  info "Compose:     $COMPOSE_FILE"
  info "Access mode: $ACCESS_MODE"
  if [[ "$ACCESS_MODE" == "public" ]]; then
    resolve_public_domain
    info "Public domain: ${PUBLIC_DOMAIN:-<unset>}"
  fi
  info "Dry-run:     $DRY_RUN"
  info "Force-reset: $FORCE_RESET"
  info "Skip-fw:     $SKIP_FIREWALL"
  info "Skip-ssh:    $SKIP_SSH_HARDENING"
  if [[ -n "$MATRIX_PASSWORD_FILE" ]]; then
    info "Matrix password file: $MATRIX_PASSWORD_FILE"
  fi
  info "=========================================="

  # Save rollback snapshot before making changes
  save_rollback_snapshot

  # Skip completed stages on re-run (idempotent resume)
  if stage_is_done 1; then
    info "Stage 1 (preflight) already passed -- re-running for safety"
  fi
  run_preflight

  if stage_is_done 2 && ! $FORCE_RESET; then
    info "Stage 2 (firewall) already completed -- skipping"
  else
    configure_firewall
  fi

  if stage_is_done 3 && ! $FORCE_RESET; then
    info "Stage 3 (config) already completed -- re-validating"
  fi
  deploy_config

  deploy_services
  configure_ssh_hardening

  # Clear stage markers on full success
  clear_stage_markers

  info "=========================================="
  info "Bootstrap complete"
  info "=========================================="
  info ""
  info "Next steps:"
  info "  1. Run the install wizard to complete device trust pairing"
  info "  2. Verify: docker compose ${COMPOSE_ARGS[*]} ps"
  info "  3. Check logs: docker compose ${COMPOSE_ARGS[*]} logs -f"
  info "  4. Room IDs are in config/.env.rooms"
  if [[ "$ACCESS_MODE" == "public" ]] || [[ "$ACCESS_MODE" == "caddy" ]]; then
    info "  5. In mobile app Setup, use homeserver URL:"
    info "     https://${PUBLIC_DOMAIN}"
    if [[ "$ACCESS_MODE" == "caddy" ]]; then
      info "  6. Verify TLS: curl https://${PUBLIC_DOMAIN}/_matrix/client/versions"
    fi
  else
    info "  5. Expose Matrix to your tailnet (keeps public internet closed):"
    info "     sudo tailscale serve --bg 8008"
    info "  6. In mobile app Setup, use homeserver URL:"
    info "     https://<your-vps-tailnet-name>"
  fi
}

main "$@"
