#!/usr/bin/env bash
# deploy-quick.sh — Lightweight VPS deployment for Caddy + Conduit + Daemon.
#
# This is a simpler alternative to bootstrap-vps.sh for users who manage
# their own VPS (SSH hardening, firewall, etc.) and just need to start
# the Symbiotic stack behind Caddy with automatic TLS.
#
# Prerequisites:
#   - Docker + Docker Compose plugin installed
#   - DNS A record pointing to this VPS (e.g. matrix.symbiotic.sh → VPS IP)
#   - Ports 80 and 443 open in firewall
#
# Usage:
#   ./scripts/deploy-quick.sh --domain matrix.symbiotic.sh
#   ./scripts/deploy-quick.sh --domain matrix.symbiotic.sh --server-name symbiotic.sh

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_DIR="$ROOT_DIR/config"
COMPOSE_FILE="$ROOT_DIR/docker-compose.vps.yml"

# Defaults
DOMAIN=""
SERVER_NAME=""
MATRIX_USER="testuser"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
info()  { echo "[INFO]  $*"; }
warn()  { echo "[WARN]  $*"; }
error() { echo "[ERROR] $*" >&2; }
die()   { error "$@"; exit 1; }

generate_hex() {
  head -c "${1:-32}" /dev/urandom | xxd -p -c 256 | tr -d '\n'
}

usage() {
  cat <<'EOF'
Usage: deploy-quick.sh [OPTIONS]

Options:
  --domain <domain>       Public Matrix domain (e.g. matrix.symbiotic.sh) [required]
  --server-name <name>    Matrix server_name for user IDs (e.g. symbiotic.sh)
                          Defaults to the --domain value
  --user <name>           Matrix username (default: testuser)
  -h, --help              Show this help
EOF
}

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)      shift; DOMAIN="${1:-}" ;;
    --server-name) shift; SERVER_NAME="${1:-}" ;;
    --user)        shift; MATRIX_USER="${1:-}" ;;
    -h|--help)     usage; exit 0 ;;
    *)             die "Unknown flag: $1" ;;
  esac
  shift
done

[[ -n "$DOMAIN" ]] || die "Missing required --domain flag. Run with --help for usage."
[[ -n "$SERVER_NAME" ]] || SERVER_NAME="$DOMAIN"

# ---------------------------------------------------------------------------
# Step 1: Check Docker
# ---------------------------------------------------------------------------
info "Checking Docker..."
command -v docker >/dev/null 2>&1 || die "Docker not found. Install: https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || die "'docker compose' plugin not found. Install docker-compose-plugin."
info "Docker OK"

# ---------------------------------------------------------------------------
# Step 2: Create .env.secrets if missing
# ---------------------------------------------------------------------------
if [[ ! -f "$CONFIG_DIR/.env.secrets" ]]; then
  info "Creating config/.env.secrets from template..."
  if [[ -f "$CONFIG_DIR/.env.secrets.template" ]]; then
    cp "$CONFIG_DIR/.env.secrets.template" "$CONFIG_DIR/.env.secrets"
  else
    cat > "$CONFIG_DIR/.env.secrets" <<SECRETS
# Symbiotic secrets — NEVER commit this file
# Generated by deploy-quick.sh
SECRETS
  fi
  # Generate vault master key
  local_vault_key=$(generate_hex 32)
  printf "\nSYMBIOTIC_VAULT_MASTER_KEY=%s\n" "$local_vault_key" >> "$CONFIG_DIR/.env.secrets"
  chmod 600 "$CONFIG_DIR/.env.secrets"
  info "Generated VAULT_MASTER_KEY in .env.secrets"
else
  info "config/.env.secrets already exists — skipping"
fi

# ---------------------------------------------------------------------------
# Step 3: Deploy conduwuit.toml with correct server_name
# ---------------------------------------------------------------------------
info "Writing config/conduwuit.toml (server_name=$SERVER_NAME)..."
sed "s/^server_name = .*/server_name = \"$SERVER_NAME\"/" \
  "$CONFIG_DIR/conduwuit.production.toml" > "$CONFIG_DIR/conduwuit.toml"
info "Conduit config ready"

# ---------------------------------------------------------------------------
# Step 4: Update .env.runtime with domain and user
# ---------------------------------------------------------------------------
info "Updating config/.env.runtime..."
runtime_file="$CONFIG_DIR/.env.runtime"

# Set public domain
if grep -q '^#\?SYMBIOTIC_MATRIX_PUBLIC_DOMAIN=' "$runtime_file" 2>/dev/null; then
  sed -i.bak "s|^#\?SYMBIOTIC_MATRIX_PUBLIC_DOMAIN=.*|SYMBIOTIC_MATRIX_PUBLIC_DOMAIN=$DOMAIN|" "$runtime_file"
  rm -f "${runtime_file}.bak"
else
  printf "\nSYMBIOTIC_MATRIX_PUBLIC_DOMAIN=%s\n" "$DOMAIN" >> "$runtime_file"
fi

# Set Matrix user
if grep -q '^SYMBIOTIC_MATRIX_USER=' "$runtime_file" 2>/dev/null; then
  sed -i.bak "s|^SYMBIOTIC_MATRIX_USER=.*|SYMBIOTIC_MATRIX_USER=$MATRIX_USER|" "$runtime_file"
  rm -f "${runtime_file}.bak"
fi

# Update allowed senders to match server_name
if grep -q '^SYMBIOTIC_ALLOWED_SENDERS=' "$runtime_file" 2>/dev/null; then
  sed -i.bak "s|^SYMBIOTIC_ALLOWED_SENDERS=.*|SYMBIOTIC_ALLOWED_SENDERS=@${MATRIX_USER}:${SERVER_NAME}|" "$runtime_file"
  rm -f "${runtime_file}.bak"
fi

info ".env.runtime updated"

# ---------------------------------------------------------------------------
# Step 5: Ensure Matrix password Docker secret
# ---------------------------------------------------------------------------
secret_dir="$CONFIG_DIR/.secrets"
secret_file="$secret_dir/matrix_password"
if [[ ! -f "$secret_file" ]]; then
  info "Generating Matrix password..."
  mkdir -p "$secret_dir"
  generate_hex 32 > "$secret_file"
  chmod 644 "$secret_file"
  info "Matrix password saved to config/.secrets/matrix_password"
else
  info "Matrix password already exists — skipping"
fi

# ---------------------------------------------------------------------------
# Step 6: Start services with Caddy profile
# ---------------------------------------------------------------------------
info "Starting services (Caddy + Conduit + Daemon)..."
docker compose -f "$COMPOSE_FILE" --profile caddy up -d

# ---------------------------------------------------------------------------
# Step 7: Wait for Conduit, then run room setup
# ---------------------------------------------------------------------------
info "Waiting for Conduit to start..."
for i in $(seq 1 30); do
  if docker compose -f "$COMPOSE_FILE" ps --format '{{.State}}' conduwuit 2>/dev/null | grep -q running; then
    break
  fi
  sleep 2
done

room_setup="$ROOT_DIR/scripts/setup-matrix-rooms.sh"
if [[ -x "$room_setup" ]]; then
  info "Running Matrix room setup..."
  # Conduit listens on 127.0.0.1:8008 in the compose config.
  # From the host, we reach it through the Caddy-forwarded port or direct.
  # Since Caddy is now on 80/443 and Conduit is 127.0.0.1:8008 (host-mapped),
  # the room setup can talk to localhost:8008.
  "$room_setup" --homeserver "http://127.0.0.1:8008" || {
    warn "Room setup had issues — daemon bootstrap will retry from inside Docker network"
  }
else
  warn "Room setup script not found at $room_setup — rooms will be created by daemon bootstrap"
fi

# ---------------------------------------------------------------------------
# Step 8: Verification checklist
# ---------------------------------------------------------------------------
echo ""
info "=========================================="
info "  Deployment complete!"
info "=========================================="
echo ""
info "Domain:      $DOMAIN"
info "Server name: $SERVER_NAME"
info "Matrix user: $MATRIX_USER"
echo ""
info "Verification checklist:"
info "  1. Check services:     docker compose -f docker-compose.vps.yml --profile caddy ps"
info "  2. Check Caddy logs:   docker compose -f docker-compose.vps.yml --profile caddy logs caddy"
info "  3. Test Matrix API:    curl https://$DOMAIN/_matrix/client/versions"
info "  4. Test well-known:    curl https://$DOMAIN/.well-known/matrix/client"
info "  5. Connect Flutter app to: https://$DOMAIN"
echo ""
info "Matrix password is in: config/.secrets/matrix_password"
info "To disable registration after bootstrap:"
info "  1. Edit config/conduwuit.toml → allow_registration = false"
info "  2. docker compose -f docker-compose.vps.yml --profile caddy restart conduwuit"
